apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbb-app-rooms-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bbb-app-rooms
    spec:
      containers:
      - name: bbb-app-rooms
        image: bigbluebutton/bbb-app-rooms:master
        ports:
        - containerPort: 3401
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: bbb-app-rooms-secrets
                key: secret-key-base
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
