default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  pool: 5
  timeout: 5000
  connect_timeout: 10

development:
  <<: *default
  database: bbb_app_rooms_development

test:
  <<: *default
  database: bbb_app_rooms_test

production:
  <<: *default
  database: bbb_app_rooms_production
